<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE students SYSTEM "students.dtd">

<!--<!DOCTYPE students [

		<!ELEMENT students (student+) >
		<!ELEMENT student (name,age,sex)>
		<!ELEMENT name (#PCDATA)>
		<!ELEMENT age (#PCDATA)>
		<!ELEMENT sex (#PCDATA)>
		<!ATTLIST student number ID #REQUIRED>
		]>-->

<students>

    <student id="1">
        <name>ITLaoXie</name>
        <age>17</age>
        <sex>boy</sex>
    </student>

    <student id="2">
        <name>XiaoSi</name>
        <age>16</age>
        <sex>boy</sex>
    </student>

</students>